In [353]:
import pandas as pd
path= 'loans_full_schema.csv'
df=pd.read_csv(path)
df

,Unnamed: 0,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,1,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,2,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,3,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,...,D1,Feb-2018,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,4,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,5,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,owner,10.0,TX,RENT,108000.0,Source Verified,22.28,NaN,NaN,...,A4,Jan-2018,Current,whole,Cash,21586.34,2969.80,2413.66,556.14,0.0
9996,9997,director,8.0,PA,MORTGAGE,121000.0,Verified,32.38,NaN,NaN,...,D3,Feb-2018,Current,whole,Cash,9147.44,1456.31,852.56,603.75,0.0
9997,9998,toolmaker,10.0,CT,MORTGAGE,67000.0,Verified,45.26,107000.0,Source Verified,...,E2,Feb-2018,Current,fractional,Cash,27617.65,4620.80,2382.35,2238.45,0.0
9998,9999,manager,1.0,WI,MORTGAGE,80000.0,Source Verified,11.99,NaN,NaN,...,A1,Feb-2018,Current,whole,Cash,21518.12,2873.31,2481.88,391.43,0.0
9999,10000,operations analyst,3.0,CT,RENT,66000.0,Not Verified,20.82,NaN,NaN,...,B4,Feb-2018,Current,whole,Cash,11574.83,1658.56,1225.17,433.39,0.0

In [354]:
df.isnull().sum()

Unnamed: 0                             0
emp_title                            833
emp_length                           817
state                                  0
homeownership                          0
annual_income                          0
verified_income                        0
debt_to_income                        24
annual_income_joint                 8505
verification_income_joint           8545
debt_to_income_joint                8505
delinq_2y                              0
months_since_last_delinq            5658
earliest_credit_line                   0
inquiries_last_12m                     0
total_credit_lines                     0
open_credit_lines                      0
total_credit_limit                     0
total_credit_utilized                  0
num_collections_last_12m               0
num_historical_failed_to_pay           0
months_since_90d_late               7715
current_accounts_delinq                0
total_collection_amount_ever           0
current_installment_accounts           0
accounts_opened_24m                    0
months_since_last_credit_inquiry    1271
num_satisfactory_accounts              0
num_accounts_120d_past_due           318
num_accounts_30d_past_due              0
num_active_debit_accounts              0
total_debit_limit                      0
num_total_cc_accounts                  0
num_open_cc_accounts                   0
num_cc_carrying_balance                0
num_mort_accounts                      0
account_never_delinq_percent           0
tax_liens                              0
public_record_bankrupt                 0
loan_purpose                           0
application_type                       0
loan_amount                            0
term                                   0
interest_rate                          0
installment                            0
grade                                  0
sub_grade                              0
issue_month                            0
loan_status                            0
initial_listing_status                 0
disbursement_method                    0
balance                                0
paid_total                             0
paid_principal                         0
paid_interest                          0
paid_late_fees                         0
dtype: int64

In [355]:
df.dropna

<bound method DataFrame.dropna of       Unnamed: 0                emp_title  emp_length state homeownership  \
0              1  global config engineer          3.0    NJ      MORTGAGE
1              2   warehouse office clerk        10.0    HI          RENT
2              3                 assembly         3.0    WI          RENT
3              4         customer service         1.0    PA          RENT
4              5     security supervisor         10.0    CA          RENT
...          ...                      ...         ...   ...           ...
9995        9996                   owner         10.0    TX          RENT
9996        9997                 director         8.0    PA      MORTGAGE
9997        9998                toolmaker        10.0    CT      MORTGAGE
9998        9999                  manager         1.0    WI      MORTGAGE
9999       10000       operations analyst         3.0    CT          RENT

      annual_income  verified_income  debt_to_income  annual_income_joint  \
0           90000.0         Verified           18.01                  NaN
1           40000.0     Not Verified            5.04                  NaN
2           40000.0  Source Verified           21.15                  NaN
3           30000.0     Not Verified           10.16                  NaN
4           35000.0         Verified           57.96              57000.0
...             ...              ...             ...                  ...
9995       108000.0  Source Verified           22.28                  NaN
9996       121000.0         Verified           32.38                  NaN
9997        67000.0         Verified           45.26             107000.0
9998        80000.0  Source Verified           11.99                  NaN
9999        66000.0     Not Verified           20.82                  NaN

     verification_income_joint  ...  sub_grade  issue_month  loan_status  \
0                          NaN  ...         C3     Mar-2018      Current
1                          NaN  ...         C1     Feb-2018      Current
2                          NaN  ...         D1     Feb-2018      Current
3                          NaN  ...         A3     Jan-2018      Current
4                     Verified  ...         C3     Mar-2018      Current
...                        ...  ...        ...          ...          ...
9995                       NaN  ...         A4     Jan-2018      Current
9996                       NaN  ...         D3     Feb-2018      Current
9997           Source Verified  ...         E2     Feb-2018      Current
9998                       NaN  ...         A1     Feb-2018      Current
9999                       NaN  ...         B4     Feb-2018      Current

      initial_listing_status  disbursement_method   balance  paid_total  \
0                      whole                 Cash  27015.86     1999.33
1                      whole                 Cash   4651.37      499.12
2                 fractional                 Cash   1824.63      281.80
3                      whole                 Cash  18853.26     3312.89
4                      whole                 Cash  21430.15     2324.65
...                      ...                  ...       ...         ...
9995                   whole                 Cash  21586.34     2969.80
9996                   whole                 Cash   9147.44     1456.31
9997              fractional                 Cash  27617.65     4620.80
9998                   whole                 Cash  21518.12     2873.31
9999                   whole                 Cash  11574.83     1658.56

      paid_principal  paid_interest  paid_late_fees
0             984.14        1015.19             0.0
1             348.63         150.49             0.0
2             175.37         106.43             0.0
3            2746.74         566.15             0.0
4            1569.85         754.80             0.0
...              ...            ...             ...
9995         2413.66         556.14             0.0
9996          852.56         603.75             0.0
9997         2382.35        2238.45             0.0
9998         2481.88         391.43             0.0
9999         1225.17         433.39             0.0

[10000 rows x 56 columns]>

In [356]:
columns_to_drop = [
    "emp_title", "state", "issue_month", "initial_listing_status",
    "disbursement_method", "balance", "paid_total", "paid_principal",
    "paid_interest", "paid_late_fees"
]

df = df.drop(columns=columns_to_drop)
df

,Unnamed: 0,emp_length,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,delinq_2y,...,public_record_bankrupt,loan_purpose,application_type,loan_amount,term,interest_rate,installment,grade,sub_grade,loan_status
0,1,3.0,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,NaN,0,...,0,moving,individual,28000,60,14.07,652.53,C,C3,Current
1,2,10.0,RENT,40000.0,Not Verified,5.04,NaN,NaN,NaN,0,...,1,debt_consolidation,individual,5000,36,12.61,167.54,C,C1,Current
2,3,3.0,RENT,40000.0,Source Verified,21.15,NaN,NaN,NaN,0,...,0,other,individual,2000,36,17.09,71.40,D,D1,Current
3,4,1.0,RENT,30000.0,Not Verified,10.16,NaN,NaN,NaN,0,...,0,debt_consolidation,individual,21600,36,6.72,664.19,A,A3,Current
4,5,10.0,RENT,35000.0,Verified,57.96,57000.0,Verified,37.66,0,...,0,credit_card,joint,23000,36,14.07,786.87,C,C3,Current
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,10.0,RENT,108000.0,Source Verified,22.28,NaN,NaN,NaN,0,...,1,other,individual,24000,36,7.35,744.90,A,A4,Current
9996,9997,8.0,MORTGAGE,121000.0,Verified,32.38,NaN,NaN,NaN,4,...,0,debt_consolidation,individual,10000,36,19.03,366.72,D,D3,Current
9997,9998,10.0,MORTGAGE,67000.0,Verified,45.26,107000.0,Source Verified,29.57,2,...,0,debt_consolidation,joint,30000,36,23.88,1175.10,E,E2,Current
9998,9999,1.0,MORTGAGE,80000.0,Source Verified,11.99,NaN,NaN,NaN,0,...,0,other,individual,24000,36,5.32,722.76,A,A1,Current
9999,10000,3.0,RENT,66000.0,Not Verified,20.82,NaN,NaN,NaN,0,...,0,credit_card,individual,12800,36,10.91,418.52,B,B4,Current

In [357]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
df['homeownership']= encoder.fit_transform(df['homeownership'])
df['verified_income']= encoder.fit_transform(df['verified_income'])
df['verification_income_joint']= encoder.fit_transform(df['verification_income_joint'])
df['loan_purpose']= encoder.fit_transform(df['loan_purpose'])
df['application_type']= encoder.fit_transform(df['application_type'])
df['grade']= encoder.fit_transform(df['grade'])
df['sub_grade']= encoder.fit_transform(df['sub_grade'])
df['loan_status']= encoder.fit_transform(df['loan_status'])

In [358]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(strategy='mean')
emp_length= df['emp_length'].values.reshape(-1,1)
df['emp_length']= imputer.fit_transform(emp_length)

In [359]:
debt_to_income= df['debt_to_income'].values.reshape(-1,1)
df['debt_to_income']= imputer.fit_transform(debt_to_income)

In [360]:
annual_income_joint= df['annual_income_joint'].values.reshape(-1,1)
df['annual_income_joint']= imputer.fit_transform(annual_income_joint)

In [361]:
debt_to_income_joint= df['debt_to_income_joint'].values.reshape(-1,1)
df['debt_to_income_joint']= imputer.fit_transform(debt_to_income_joint)

In [362]:
months_since_last_delinq= df['months_since_last_delinq'].values.reshape(-1,1)
df['months_since_last_delinq']= imputer.fit_transform(months_since_last_delinq)

In [363]:
months_since_90d_late= df['months_since_90d_late'].values.reshape(-1,1)
df['months_since_90d_late']= imputer.fit_transform(months_since_90d_late)

In [364]:
months_since_last_credit_inquiry= df['months_since_last_credit_inquiry'].values.reshape(-1,1)
df['months_since_last_credit_inquiry']= imputer.fit_transform(months_since_last_credit_inquiry)

In [365]:
start_col = 'months_since_last_credit_inquiry'
end_col = 'installment'

start_index = df.columns.get_loc(start_col)
end_index = df.columns.get_loc(end_col)

columns_in_range = df.columns[start_index:end_index+1]

null_values_in_range = df[columns_in_range].isnull().sum()
print(null_values_in_range)

months_since_last_credit_inquiry      0
num_satisfactory_accounts             0
num_accounts_120d_past_due          318
num_accounts_30d_past_due             0
num_active_debit_accounts             0
total_debit_limit                     0
num_total_cc_accounts                 0
num_open_cc_accounts                  0
num_cc_carrying_balance               0
num_mort_accounts                     0
account_never_delinq_percent          0
tax_liens                             0
public_record_bankrupt                0
loan_purpose                          0
application_type                      0
loan_amount                           0
term                                  0
interest_rate                         0
installment                           0
dtype: int64

In [366]:
num_accounts_120d_past_due= df['num_accounts_120d_past_due'].values.reshape(-1,1)
df['num_accounts_120d_past_due']= imputer.fit_transform(num_accounts_120d_past_due)

In [367]:
df.isnull().sum()

Unnamed: 0                          0
emp_length                          0
homeownership                       0
annual_income                       0
verified_income                     0
debt_to_income                      0
annual_income_joint                 0
verification_income_joint           0
debt_to_income_joint                0
delinq_2y                           0
months_since_last_delinq            0
earliest_credit_line                0
inquiries_last_12m                  0
total_credit_lines                  0
open_credit_lines                   0
total_credit_limit                  0
total_credit_utilized               0
num_collections_last_12m            0
num_historical_failed_to_pay        0
months_since_90d_late               0
current_accounts_delinq             0
total_collection_amount_ever        0
current_installment_accounts        0
accounts_opened_24m                 0
months_since_last_credit_inquiry    0
num_satisfactory_accounts           0
num_accounts_120d_past_due          0
num_accounts_30d_past_due           0
num_active_debit_accounts           0
total_debit_limit                   0
num_total_cc_accounts               0
num_open_cc_accounts                0
num_cc_carrying_balance             0
num_mort_accounts                   0
account_never_delinq_percent        0
tax_liens                           0
public_record_bankrupt              0
loan_purpose                        0
application_type                    0
loan_amount                         0
term                                0
interest_rate                       0
installment                         0
grade                               0
sub_grade                           0
loan_status                         0
dtype: int64

In [368]:
X= df.drop(columns='loan_status')
y= df['loan_status']

In [369]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
standardized_features= scaler.fit_transform(X)

In [370]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(standardized_features, y, test_size=0.2, random_state=42)

In [371]:
X_train = X_train.astype(int)
X_test = X_test.astype(int)

In [372]:
print(X_train.dtype)
print(y_train.dtype)
print(X_test.dtype)
print(y_test.dtype)

int32
int32
int32
int32

In [373]:
from sklearn.tree import DecisionTreeClassifier
tree= DecisionTreeClassifier()
tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [374]:
y_pred= tree.predict(X_test)
y_pred

array([1, 1, 2, ..., 1, 1, 1])

In [375]:
# y_pred_proba = tree.predict_proba(X_test)  # Probability of the positive class

In [376]:
# import numpy as np

# num_classes = len(np.unique(y_test))
# print("Number of unique classes in y_test:", num_classes)

In [377]:
# print("Shape of y_pred_proba:", y_pred_proba.shape)

In [378]:
# from sklearn.preprocessing import normalize

# y_pred_proba_filtered = normalize(y_pred_proba_filtered, norm='l1', axis=1)

In [379]:
# from sklearn.preprocessing import normalize
# y_pred_proba_filtered = y_pred_proba.reshape(1, -1)

# y_pred_proba_filtered = normalize(y_pred_proba_filtered, norm='l1', axis=1)

In [380]:
# all_zero_rows = np.where(~y_pred_proba_filtered.any(axis=1))[0]

# if len(all_zero_rows) > 0:
#     print(f"Found {len(all_zero_rows)} rows with all zeros in y_pred_proba_filtered.")
# else:
#     print("No rows with all zeros found in y_pred_proba_filtered.")

In [381]:
# import numpy as np
# from sklearn.metrics import roc_auc_score

# mask = ~np.all(y_pred_proba_filtered == 0, axis=1)
# y_pred_proba_filtered = y_pred_proba_filtered[mask]

# y_test_np = y_test.values

# mask_test = np.isin(np.arange(len(y_test_np)), np.where(mask)[0])
# y_test_np = y_test_np[mask_test]

# roc_auc = roc_auc_score(y_test_np, y_pred_proba_filtered, multi_class='ovr', average='macro')
# print("ROC AUC Score:", roc_auc)

In [382]:
print(y_test.dtype)
print(y_pred.dtype)

int32
int32

In [394]:
from sklearn.metrics import accuracy_score, roc_auc_score

accuracy= accuracy_score(y_test, y_pred)

# roc_auc_score= roc_auc_score(y_test, y_pred)

 Predicting Hospital Readmission Using Logistic Regression

    Dataset:

Hospital Readmission Dataset

    Preprocessing Steps:

Handle missing values (e.g., fill missing values with mode for categorical variables).

Encode categorical variables (e.g., one-hot encoding for hospital type, region, etc.).

Standardize numerical features.

    Task:
    
Implement logistic regression to predict hospital readmission and evaluate the model using precision, recall, and F1-score.

In [384]:
import pandas as pd
df=pd.read_csv('hospital_readmissions.csv')
df

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,[80-90),14,77,1,30,0,0,0,Missing,Circulatory,Other,Circulatory,no,normal,no,no,yes
24996,[80-90),2,66,0,24,0,0,0,Missing,Digestive,Injury,Other,no,high,yes,yes,yes
24997,[70-80),5,12,0,6,0,1,0,Missing,Other,Other,Other,normal,no,no,no,yes
24998,[70-80),2,61,3,15,0,0,0,Family/GeneralPractice,Respiratory,Diabetes,Other,no,no,yes,yes,no
24999,[50-60),10,37,1,24,0,0,0,Missing,Other,Diabetes,Circulatory,no,no,no,no,yes

In [385]:
df.dropna()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,[80-90),14,77,1,30,0,0,0,Missing,Circulatory,Other,Circulatory,no,normal,no,no,yes
24996,[80-90),2,66,0,24,0,0,0,Missing,Digestive,Injury,Other,no,high,yes,yes,yes
24997,[70-80),5,12,0,6,0,1,0,Missing,Other,Other,Other,normal,no,no,no,yes
24998,[70-80),2,61,3,15,0,0,0,Family/GeneralPractice,Respiratory,Diabetes,Other,no,no,yes,yes,no
24999,[50-60),10,37,1,24,0,0,0,Missing,Other,Diabetes,Circulatory,no,no,no,no,yes

In [386]:
df.isnull().sum()

age                  0
time_in_hospital     0
n_lab_procedures     0
n_procedures         0
n_medications        0
n_outpatient         0
n_inpatient          0
n_emergency          0
medical_specialty    0
diag_1               0
diag_2               0
diag_3               0
glucose_test         0
A1Ctest              0
change               0
diabetes_med         0
readmitted           0
dtype: int64

In [387]:
from sklearn.preprocessing import OneHotEncoder
encoder= OneHotEncoder(sparse_output=False)
medical_specialty = df['medical_specialty'].values.reshape(-1, 1)
df['medical_specialty']=encoder.fit_transform(medical_specialty)

age = df['age'].values.reshape(-1, 1)
df['age']=encoder.fit_transform(age)


diag_1 = df['diag_1'].values.reshape(-1, 1)
df['diag_1']=encoder.fit_transform(diag_1)


diag_2 = df['diag_2'].values.reshape(-1, 1)
df['diag_2']=encoder.fit_transform(diag_2)



diag_3 = df['diag_3'].values.reshape(-1, 1)
df['diag_3']=encoder.fit_transform(diag_3)



A1Ctest = df['A1Ctest'].values.reshape(-1, 1)
df['A1Ctest']=encoder.fit_transform(A1Ctest)

change = df['change'].values.reshape(-1, 1)
df['change']=encoder.fit_transform(change)


diabetes_med = df['diabetes_med'].values.reshape(-1, 1)
df['diabetes_med']=encoder.fit_transform(diabetes_med)



readmitted = df['readmitted'].values.reshape(-1, 1)
df['readmitted']=encoder.fit_transform(readmitted)

glucose_test = df['glucose_test'].values.reshape(-1, 1)
df['glucose_test']=encoder.fit_transform(glucose_test)


df

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,0.0,8,72,1,18,2,0,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,0.0,3,34,2,13,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,0.0,5,45,0,18,0,0,0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,2,36,0,12,1,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1,42,0,7,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.0,14,77,1,30,0,0,0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
24996,0.0,2,66,0,24,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
24997,0.0,5,12,0,6,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
24998,0.0,2,61,3,15,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
24999,0.0,10,37,1,24,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0

In [388]:
X=df.drop(columns='readmitted')
y=df['readmitted']

In [389]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaled= scaler.fit_transform(X)

In [390]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaled, y, test_size=0.2, random_state=42)

In [391]:
from sklearn.linear_model import LogisticRegression
regression= LogisticRegression()
regression.fit(X_train,y_train)

LogisticRegression()

In [392]:
y_pred=regression.predict(X_test)
# print('predict: ', y_pred)
y_pred

array([0., 1., 1., ..., 0., 1., 1.])

In [393]:
from sklearn.metrics import precision_score, recall_score, f1_score
precision= precision_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
f1_score= f1_score(y_test, y_pred)

print("Precision: ", precision)
print("Recall Score: ", recall)
print("f1 score: ", f1_score)

Precision:  0.6050828098229583
Recall Score:  0.7972159518434914
f1 score:  0.687987012987013

3. Classifying Digit Images Using Decision Trees

    Dataset:

MNIST Dataset

    Preprocessing Steps:

Normalize pixel values.

Reshape data as needed for model input.

    Task:
    
Implement a decision tree classifier to classify handwritten digits and evaluate the model using accuracy and confusion matrix.